### ISSUE TITLE
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False.

### ISSUE THREAD

**Issue by harshrathod50** [achieveordie/IsItCorrect#4]
The Fedora 23 Server OS is a Virtual Private Server. It has CPU with one core only. There is no GPU. I get this error:

```
[root@vps47654603 is-it-correct]# python3.8 app.py
Calling CamembertTokenizer.from_pretrained() with the path to a single file or url is deprecated
Traceback (most recent call last):
  File "app.py", line 27, in <module>
    model = load_model(save_model_location)
  File "app.py", line 22, in load_model
    model.load_state_dict(torch.load(save_model_location))
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 765, in _legacy_load
    result = unpickler.load()
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 721, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 174, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 150, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 134, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Comment by achieveordie** [comment]
I've pushed the following change into the repo:
```
def load_model(save_model_location):
    model = getCustomModel()
    if not torch.cuda.is_available():
        model.load_state_dict(torch.load(save_model_location, map_location='cpu'))
    else:
        model.load_state_dict(torch.load(save_model_location))
```
this should work in our case. Do a pull and let me know.

**Comment by harshrathod50** [comment]
Yes, this is the exact logic we needed. This solved the error.

**Comment by arfabee** [comment]
Sorry I'm a newbie, in which file did you push the line above? Thanks!

**Comment by achieveordie** [comment]
> Sorry I'm a newbie, in which file did you push the line above? Thanks!

The above code need not be written as a function and it is supposed to added wherever you are loading your model for inference.

Here's a link that may assist you further - https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-model-across-devices
